### ISSUE TITLE
orangepizero Channel 7 is already configured

### ISSUE THREAD

**Issue by qsoMaster** [arek125/remote-GPIO-control-server#10]
Board : Orange PI Zero Sytem : Armbian 22.08.2 Buster with Linux 5.15.69-sunxi
Hi , service is working , web interface is available but an error occurs when configuring outputs .
 
![20221009-155621-002](https://user-images.githubusercontent.com/11243316/194759299-32278bf9-4a63-4b39-8dc7-d2d9aaeac851.jpg)
![20221009-155639-003](https://user-images.githubusercontent.com/11243316/194759317-909f1cca-78ae-4f19-96ed-ae8a49a04d1a.jpg)
![20221009-155600-001](https://user-images.githubusercontent.com/11243316/194759320-65255088-b95b-444d-a7c5-eb715a125d8d.jpg)
output: journalctl -u rgc.service -r
Oct 09 16:24:12 orangepizero python[1327]: REPLY: true;HR_selByCat;28;2022-10-09 13:23:43.901036;WEB;7;ON;27;2022-10-09
Oct 09 16:24:12 orangepizero python[1327]: SIZE: 49b
Oct 09 16:24:12 orangepizero python[1327]: REPLY: true;GPIO_Olist;3;7;2;7;0;1;
Oct 09 16:24:12 orangepizero python[1327]: RECIVED: 1;GPIO_Olist;WEB;
Oct 09 16:24:12 orangepizero python[1327]: RECIVED: 1;HR_selByCat;2022-10-01;2022-10-10;i/o;WEB;
Oct 09 16:24:12 orangepizero python[1327]: RECIVED: 1;GPIO_set;3;7;0;2022-10-09 13:23:48.159;0;WEB;
Oct 09 16:24:12 orangepizero python[1327]: SIZE: 627b
Oct 09 16:24:12 orangepizero python[1327]: -09 13:01:33.446889;WEB;7;ON;24;2022-10-09 13:01:32.385164;WEB;7;ON;23;2022-1
Oct 09 16:24:12 orangepizero python[1327]: 10.20.241.122 - - [09/Oct/2022 16:24:12] "POST / HTTP/1.1" 200 -
Oct 09 16:24:07 orangepizero python[1327]: 10.20.241.122 - - [09/Oct/2022 16:24:07] "POST / HTTP/1.1" 200 -
Oct 09 16:24:07 orangepizero python[1327]: 10.20.241.122 - - [09/Oct/2022 16:24:07] "POST / HTTP/1.1" 200 -
Oct 09 16:24:02 orangepizero python[1327]: 10.20.241.122 - - [09/Oct/2022 16:24:02] "POST / HTTP/1.1" 200 -
Oct 09 16:24:02 orangepizero python[1327]: 10.20.241.122 - - [09/Oct/2022 16:24:02] "POST / HTTP/1.1" 200 -
Oct 09 16:23:57 orangepizero python[1327]: 10.20.241.122 - - [09/Oct/2022 16:23:57] "POST / HTTP/1.1" 200 -
Oct 09 16:23:57 orangepizero python[1327]: 10.20.241.122 - - [09/Oct/2022 16:23:57] "POST / HTTP/1.1" 200 -
Oct 09 16:23:52 orangepizero python[1327]: 10.20.241.122 - - [09/Oct/2022 16:23:52] "POST / HTTP/1.1" 200 -
Oct 09 16:23:52 orangepizero python[1327]: 10.20.241.122 - - [09/Oct/2022 16:23:52] "POST / HTTP/1.1" 200 -
Oct 09 16:23:48 orangepizero python[1327]: 10.20.241.122 - - [09/Oct/2022 16:23:48] "POST / HTTP/1.1" 500 -
Oct 09 16:23:48 orangepizero rgc-server.py[1327]: Traceback (most recent call last):
                                                    File "rgc-server.py", line 1463, in do_POST
                                                      reply = requestMethod(data)
                                                    File "rgc-server.py", line 843, in requestMethod
                                                      GPIOset(datalist[3], datalist[4])
                                                    File "rgc-server.py", line 480, in GPIOset
                                                      GPIO.setup(pin, GPIO.OUT)
                                                    File "/usr/local/lib/python2.7/dist-packages/OPi/GPIO.py", line 469,
                                                      raise RuntimeError("Channel {0} is already configured".format(chan
                                                  RuntimeError: Channel 7 is already configured
Oct 09 16:23:48 orangepizero rgc-server.py[1327]: Channel 7 is already configured
Oct 09 16:23:47 orangepizero python[1327]: REPLY: true;HR_selByCat;28;2022-10-09 13:23:43.901036;WEB;7;ON;27;2022-10-09
Oct 09 16:23:47 orangepizero python[1327]: SIZE: 49b
Oct 09 16:23:47 orangepizero python[1327]: REPLY: true;GPIO_Olist;3;7;2;7;0;1;
Oct 09 16:23:47 orangepizero python[1327]: RECIVED: 1;GPIO_Olist;WEB;
Oct 09 16:23:47 orangepizero python[1327]: RECIVED: 1;HR_selByCat;2022-10-01;2022-10-10;i/o;WEB;
Oct 09 16:23:47 orangepizero python[1327]: RECIVED: 1;GPIO_set;3;7;0;2022-10-09 13:23:46.995;0;WEB;
Oct 09 16:23:47 orangepizero python[1327]: RECIVED: 1;GPIO_set;3;7;1;2022-10-09 13:23:45.505;0;WEB;
Oct 09 16:23:47 orangepizero python[1327]: SIZE: 61b
Oct 09 16:23:47 orangepizero python[1327]: REPLY: true;GPIO_set;2;2022-10-09 13:23:43.465;
Oct 09 16:23:47 orangepizero python[1327]: RECIVED: 1;GPIO_set;3;7;2;2022-10-09 13:23:43.465;0;WEB;
Oct 09 16:23:47 orangepizero python[1327]: RECIVED: 1;GPIO_set;3;7;0;2022-10-09 13:23:43.402;0;WEB;
Oct 09 16:23:47 orangepizero python[1327]: SIZE: 588b
Oct 09 16:23:47 orangepizero python[1327]: REPLY: true;HR_selByCat;27;2022-10-09 13:15:21.002926;WEB;7;ON;26;2022-10-09
lines 118-155

**Comment by qsoMaster** [comment]
![20221009-162912-004](https://user-images.githubusercontent.com/11243316/194759615-0bd12488-0879-4a4b-b28e-a3c49988bd37.jpg)

**Comment by mdi-9** [comment]
Error is coming from lib: https://opi-gpio.readthedocs.io
Check if it will be working directly from simple python script.

**Comment by qsoMaster** [comment]
#!/usr/bin/env python
import OPi.GPIO as GPIO
import time
PIN_NUM = 7

GPIO.setmode(GPIO.BOARD)
GPIO.setup(PIN_NUM,GPIO.OUT)
while True:
        GPIO.output(PIN_NUM,True)
        time.sleep(1)
        GPIO.output(PIN_NUM,False)
        time.sleep(1)

This working . Check gpio readall .
![20221010-190809-001](https://user-images.githubusercontent.com/11243316/194909818-af785b2d-8daf-449e-94d4-1226f8c5f025.jpg)

**Comment by mdi-9** [comment]
try with: GPIO.setmode(GPIO.BCM)

**Comment by qsoMaster** [comment]
HI, GPIO.setmode(GPIO.BCM) or BOARD doesn't change anything .

**Comment by mdi-9** [comment]
Replace your main server file with [this](https://github.com/arek125/remote-GPIO-control-server/blob/master/pizero/rgc-server.py).

**Comment by qsoMaster** [comment]
Hello . I am testing GPIO(BCM) 7 push button - working , but in interface sometimes pops up - `invalid literal for int() with base 10: 'undefined'` , checking pinouts `watch -n 1 gpio readall` logical state changing but sometimes unstable maybe stay log 1 or 0 .

**Comment by qsoMaster** [comment]
`journalctl -u rgc.service -r`
ct 12 18:08:35 OrangePi python[17596]: REPLY: true;GPIO_Olist;10;7;0;7;0;1;
Oct 12 18:08:35 OrangePi python[17596]: RECIVED: 1;GPIO_Olist;WEB;
Oct 12 18:08:35 OrangePi python[17596]: SIZE: 61b
Oct 12 18:08:35 OrangePi python[17596]: REPLY: true;GPIO_set;0;2022-10-12 18:08:11.920;
Oct 12 18:08:35 OrangePi python[17596]: RECIVED: 1;GPIO_set;10;7;0;2022-10-12 18:08:11.920;0;WEB;
Oct 12 18:08:35 OrangePi python[17596]: SIZE: 324b
Oct 12 18:08:35 OrangePi python[17596]: :07:57.877277;WEB;7;OFF;166;2022-10-12 18:07:56.162675;WEB;7;ON;165;2022-10-12 18:07:54.154758;WEB;7;OFF;164;2022-10-12 18:07:54.084671;W
Oct 12 18:08:33 OrangePi python[17596]: 10.20.241.3 - - [12/Oct/2022 18:08:33] "POST / HTTP/1.1" 200 -
Oct 12 18:08:30 OrangePi python[17596]: 10.20.241.3 - - [12/Oct/2022 18:08:30] "POST / HTTP/1.1" 500 -
Oct 12 18:08:30 OrangePi rgc-server.py[17596]: Traceback (most recent call last):
                                                 File "rgc-server.py", line 1470, in do_POST
                                                   reply = requestMethod(data)
                                                 File "rgc-server.py", line 850, in requestMethod
                                                   GPIOset(datalist[3], datalist[4])
                                                 File "rgc-server.py", line 476, in GPIOset
                                                   onoff = int(onoff)
                                               ValueError: invalid literal for int() with base 10: 'undefined'
Oct 12 18:08:30 OrangePi rgc-server.py[17596]: invalid literal for int() with base 10: 'undefined'
Oct 12 18:08:30 OrangePi python[17596]: 10.20.241.3 - - [12/Oct/2022 18:08:30] "POST / HTTP/1.1" 200 -
Oct 12 18:08:28 OrangePi python[17596]: 10.20.241.3 - - [12/Oct/2022 18:08:28] "POST / HTTP/1.1" 200 -
Oct 12 18:08:26 OrangePi python[17596]: 10.20.241.3 - - [12/Oct/2022 18:08:26] "POST / HTTP/1.1" 200 -
Oct 12 18:08:25 OrangePi python[17596]: 10.20.241.3 - - [12/Oct/2022 18:08:25] "POST / HTTP/1.1" 200 -
Oct 12 18:08:24 OrangePi python[17596]: 10.20.241.3 - - [12/Oct/2022 18:08:24] "POST / HTTP/1.1" 200 -
Oct 12 18:08:24 OrangePi python[17596]: 10.20.241.3 - - [12/Oct/2022 18:08:24] "POST / HTTP/1.1" 200 -
Oct 12 18:08:23 OrangePi python[17596]: 10.20.241.3 - - [12/Oct/2022 18:08:23] "POST / HTTP/1.1" 200 -
Oct 12 18:08:20 OrangePi python[17596]: 10.20.241.3 - - [12/Oct/2022 18:08:20] "POST / HTTP/1.1" 200 -
Oct 12 18:08:20 OrangePi python[17596]: 10.20.241.3 - - [12/Oct/2022 18:08:20] "POST / HTTP/1.1" 200 -
Oct 12 18:08:19 OrangePi python[17596]: 10.20.241.3 - - [12/Oct/2022 18:08:19] "POST / HTTP/1.1" 200 -
Oct 12 18:08:18 OrangePi python[17596]: 10.20.241.3 - - [12/Oct/2022 18:08:18] "POST / HTTP/1.1" 200 -
Oct 12 18:08:15 OrangePi python[17596]: 10.20.241.3 - - [12/Oct/2022 18:08:15] "POST / HTTP/1.1" 500 -

**Comment by mdi-9** [comment]
A quick fix in the same file.

**Comment by qsoMaster** [comment]
Thanks , I'm testing I'll tellabout the results later.

**Comment by qsoMaster** [comment]
Тow this
`invalid input syntax for integer: "undefined" LINE 1: UPDATE stany set Stan ='undefined',Edit_time='2022-10-28 14:... ^
`
