### ISSUE TITLE
Can't connect to the server!

### ISSUE THREAD

**Issue by Labeeb97** [arek125/remote-GPIO-control-server#7]
I just completed the installation, i run sudo systemctl status rgc.service, i got the following:

\u25cf rgc.service - Remote GPIO Control Server
   Loaded: loaded (/lib/systemd/system/rgc.service; enabled; vendor preset: enab
   Active: activating (auto-restart) (Result: exit-code) since Sat 2021-04-17 23
  Process: 8241 ExecStart=/usr/bin/python rgc-server.py (code=exited, status=1/F
 Main PID: 8241 (code=exited, status=1/FAILURE)

So, what exactly i missed here?

**Comment by mdi-9** [comment]
show me: journalctl -u rgc.service -r

**Comment by Labeeb97** [comment]
sure:

pi@LABEEB3B:~ $ journalctl -u rgc.service -r
-- Logs begin at Thu 2019-02-14 14:11:59 +04, end at Sun 2021-04-18 10:01:56 +04
Apr 18 10:01:56 LABEEB3B systemd[1]: rgc.service: Failed with result 'exit-code'
Apr 18 10:01:56 LABEEB3B systemd[1]: rgc.service: Main process exited, code=exit
Apr 18 10:01:56 LABEEB3B python[1861]: ImportError: No module named systemd.jour
Apr 18 10:01:56 LABEEB3B python[1861]:     from systemd.journal import JournalHa
Apr 18 10:01:56 LABEEB3B python[1861]:   File "rgc-server.py", line 15, in <modu
Apr 18 10:01:56 LABEEB3B python[1861]: Traceback (most recent call last):
Apr 18 10:01:56 LABEEB3B systemd[1]: Started Remote GPIO Control Server.
Apr 18 10:01:56 LABEEB3B systemd[1]: Stopped Remote GPIO Control Server.
Apr 18 10:01:56 LABEEB3B systemd[1]: rgc.service: Scheduled restart job, restart
Apr 18 10:01:56 LABEEB3B systemd[1]: rgc.service: Service RestartSec=3s expired,
Apr 18 10:01:53 LABEEB3B systemd[1]: rgc.service: Failed with result 'exit-code'
Apr 18 10:01:53 LABEEB3B systemd[1]: rgc.service: Main process exited, code=exit
Apr 18 10:01:53 LABEEB3B python[1860]: ImportError: No module named systemd.jour
Apr 18 10:01:53 LABEEB3B python[1860]:     from systemd.journal import JournalHa
Apr 18 10:01:53 LABEEB3B python[1860]:   File "rgc-server.py", line 15, in <modu
Apr 18 10:01:53 LABEEB3B python[1860]: Traceback (most recent call last):
Apr 18 10:01:52 LABEEB3B systemd[1]: Started Remote GPIO Control Server.
Apr 18 10:01:52 LABEEB3B systemd[1]: Stopped Remote GPIO Control Server.
Apr 18 10:01:52 LABEEB3B systemd[1]: rgc.service: Scheduled restart job, restart
Apr 18 10:01:52 LABEEB3B systemd[1]: rgc.service: Service RestartSec=3s expired,
Apr 18 10:01:49 LABEEB3B systemd[1]: rgc.service: Failed with result 'exit-code'
Apr 18 10:01:49 LABEEB3B systemd[1]: rgc.service: Main process exited, code=exit
lines 1-23

**Comment by mdi-9** [comment]
Package python-systemd is missing, if it cannot be installed via apt, then add backports to repository, guide is in docs.

**Comment by Labeeb97** [comment]
I got this!:

pi@LABEEB3B:~ $ sudo apt-get install certbot -t stretch-backports
Reading package lists... Done
E: The value 'stretch-backports' is invalid for APT::Default-Release as such a release is not available in the sources

**Comment by mdi-9** [comment]
I'am sure thats not from my docs,

This is:
```
sudo nano /etc/apt/sources.list
Paste line:
For stretch: deb http://archive.debian.org/debian stretch-backports main
For jessie: deb http://archive.debian.org/debian jessie-backports main
sudo apt-get update
```

**Comment by Labeeb97** [comment]
i followed your doc, i got the following:

pi@LABEEB3B:~ $ sudo apt-get update
Get:1 http://ftp.debian.org/debian stretch-backports InRelease [91.8 kB]
Hit:2 http://archive.raspberrypi.org/debian buster InRelease                   
Hit:3 http://raspbian.raspberrypi.org/raspbian buster InRelease                
Ign:4 http://archive.debian.org/debian stretch-backports InRelease
Err:5 http://archive.debian.org/debian stretch-backports Release
  404  Not Found [IP: 193.62.202.28 80]
Get:6 http://archive.debian.org/debian jessie-backports InRelease [166 kB]
Err:1 http://ftp.debian.org/debian stretch-backports InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 04EE7237B7D453EC NO_PUBKEY 648ACFD622F3D138
Err:6 http://archive.debian.org/debian jessie-backports InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8B48AD6246925553 NO_PUBKEY 7638D0442B90D010
Reading package lists... Done
E: The repository 'http://archive.debian.org/debian stretch-backports Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://ftp.debian.org/debian stretch-backports InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 04EE7237B7D453EC NO_PUBKEY 648ACFD622F3D138
E: The repository 'http://ftp.debian.org/debian stretch-backports InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://archive.debian.org/debian jessie-backports InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8B48AD6246925553 NO_PUBKEY 7638D0442B90D010
E: The repository 'http://archive.debian.org/debian jessie-backports InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by mdi-9** [comment]
Remove jessie entres, You have stretch rls
And try to import keys:
```
sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80  --recv-keys 04EE7237B7D453EC
sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80  --recv-keys 648ACFD622F3D138
```

**Comment by Labeeb97** [comment]
Look at this:

pi@LABEEB3B:~ $ sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80  --recv-keys 04EE7237B7D453EC
Executing: /tmp/apt-key-gpghome.mOvM5hRnRI/gpg.1.sh --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 04EE7237B7D453EC
gpg: keyserver receive failed: Network is unreachable
pi@LABEEB3B:~ $ sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80  --recv-keys 648ACFD622F3D138
Executing: /tmp/apt-key-gpghome.T8EJ2hAD3q/gpg.1.sh --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 648ACFD622F3D138
gpg: key DC30D7C23CBBABEE: "Debian Archive Automatic Signing Key (10/buster) <ftpmaster@debian.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1



pi@LABEEB3B:~ $ sudo apt-get update
Hit:1 http://ftp.debian.org/debian stretch-backports InRelease
Hit:2 http://archive.raspberrypi.org/debian buster InRelease                   
Ign:3 http://archive.debian.org/debian stretch-backports InRelease             
Hit:4 http://raspbian.raspberrypi.org/raspbian buster InRelease
Err:5 http://archive.debian.org/debian stretch-backports Release
  404  Not Found [IP: 193.62.202.28 80]
Reading package lists... Done
E: The repository 'http://archive.debian.org/debian stretch-backports Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by mdi-9** [comment]
Look for keyserver that is reachable from your network.

**Comment by Labeeb97** [comment]
I am connected now with the server, but i am not able connect through mobile app! i run the following command:
pi@LABEEB3B:~ $  journalctl -u rgc.service -r
-- Logs begin at Sun 2021-04-18 15:55:36 +04, end at Sun 2021-04-18 16:32:55 +04
Apr 18 16:32:55 LABEEB3B systemd[1]: Started Remote GPIO Control Server.
Apr 18 16:32:55 LABEEB3B systemd[1]: Stopped Remote GPIO Control Server.
Apr 18 16:32:55 LABEEB3B systemd[1]: rgc.service: Scheduled restart job, restart
Apr 18 16:32:55 LABEEB3B systemd[1]: rgc.service: Service RestartSec=3s expired,
Apr 18 16:32:52 LABEEB3B systemd[1]: rgc.service: Failed with result 'exit-code'
Apr 18 16:32:52 LABEEB3B systemd[1]: rgc.service: Main process exited, code=exit
Apr 18 16:32:52 LABEEB3B python[3430]: ImportError: No module named systemd.jour
Apr 18 16:32:52 LABEEB3B python[3430]:     from systemd.journal import JournalHa
Apr 18 16:32:52 LABEEB3B python[3430]:   File "rgc-server.py", line 15, in <modu
Apr 18 16:32:52 LABEEB3B python[3430]: Traceback (most recent call last):
Apr 18 16:32:52 LABEEB3B systemd[1]: Started Remote GPIO Control Server.
Apr 18 16:32:52 LABEEB3B systemd[1]: Stopped Remote GPIO Control Server.
Apr 18 16:32:52 LABEEB3B systemd[1]: rgc.service: Scheduled restart job, restart
Apr 18 16:32:52 LABEEB3B systemd[1]: rgc.service: Service RestartSec=3s expired,
Apr 18 16:32:49 LABEEB3B systemd[1]: rgc.service: Failed with result 'exit-code'
Apr 18 16:32:49 LABEEB3B systemd[1]: rgc.service: Main process exited, code=exit
Apr 18 16:32:49 LABEEB3B python[3423]: ImportError: No module named systemd.jour
Apr 18 16:32:49 LABEEB3B python[3423]:     from systemd.journal import JournalHa
Apr 18 16:32:49 LABEEB3B python[3423]:   File "rgc-server.py", line 15, in <modu
Apr 18 16:32:49 LABEEB3B python[3423]: Traceback (most recent call last):
Apr 18 16:32:48 LABEEB3B systemd[1]: Started Remote GPIO Control Server.
Apr 18 16:32:48 LABEEB3B systemd[1]: Stopped Remote GPIO Control Server.
lines 1-23

**Comment by Labeeb97** [comment]
it gives me: ERROR:java.net.SocketTimeoutException: Poll timed out

**Comment by mdi-9** [comment]
Still have same error, if u add backports successfully then repeat install: ```sudo apt-get install python-systemd```

**Comment by Labeeb97** [comment]
i got this:

pi@LABEEB3B:~ $ sudo apt-get install python-systemd
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  python-systemd
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 32.6 kB of archives.
After this operation, 153 kB of additional disk space will be used.
Get:1 http://mirror.nl.leaseweb.net/raspbian/raspbian buster/main armhf python-systemd armhf 234-2+b1 [32.6 kB]
Fetched 32.6 kB in 1min 2s (527 B/s)                   
Selecting previously unselected package python-systemd.
(Reading database ... 103845 files and directories currently installed.)
Preparing to unpack .../python-systemd_234-2+b1_armhf.deb ...
Unpacking python-systemd (234-2+b1) ...
Setting up python-systemd (234-2+b1) ...

**Comment by mdi-9** [comment]
looks ok

**Comment by Labeeb97** [comment]
Still gives me from mobile app: ERROR:java.net.SocketTimeoutException: Poll timed out

**Comment by mdi-9** [comment]
did u restart after installation ?  show logs and status

**Comment by Labeeb97** [comment]
after i restart i got this:

pi@LABEEB3B:~ $ sudo systemctl status rgc.service
* rgc.service - Remote GPIO Control Server
   Loaded: loaded (/lib/systemd/system/rgc.service; enabled; vendor preset: enab
   Active: activating (auto-restart) (Result: exit-code) since Sun 2021-04-18 21
  Process: 1690 ExecStart=/usr/bin/python rgc-server.py (code=exited, status=1/F
 Main PID: 1690 (code=exited, status=1/FAILURE)
lines 1-5/5 (END)

**Comment by Labeeb97** [comment]
with this logs:

pi@LABEEB3B:~ $ journalctl -u rgc.service
-- Logs begin at Sun 2021-04-18 21:04:03 +04, end at Sun 2021-04-18 21:16:29 +04
Apr 18 21:04:15 LABEEB3B systemd[1]: Started Remote GPIO Control Server.
Apr 18 21:04:17 LABEEB3B python[574]: Traceback (most recent call last):
Apr 18 21:04:17 LABEEB3B python[574]:   File "rgc-server.py", line 33, in <modul
Apr 18 21:04:17 LABEEB3B python[574]:     import psycopg2
Apr 18 21:04:17 LABEEB3B python[574]: ImportError: No module named psycopg2
Apr 18 21:04:17 LABEEB3B systemd[1]: rgc.service: Main process exited, code=exit
Apr 18 21:04:17 LABEEB3B systemd[1]: rgc.service: Failed with result 'exit-code'
Apr 18 21:04:20 LABEEB3B systemd[1]: rgc.service: Service RestartSec=3s expired,
Apr 18 21:04:20 LABEEB3B systemd[1]: rgc.service: Scheduled restart job, restart
Apr 18 21:04:20 LABEEB3B systemd[1]: Stopped Remote GPIO Control Server.
Apr 18 21:04:20 LABEEB3B systemd[1]: Started Remote GPIO Control Server.
Apr 18 21:04:21 LABEEB3B python[780]: Traceback (most recent call last):
Apr 18 21:04:21 LABEEB3B python[780]:   File "rgc-server.py", line 33, in <modul
Apr 18 21:04:21 LABEEB3B python[780]:     import psycopg2
Apr 18 21:04:21 LABEEB3B python[780]: ImportError: No module named psycopg2
Apr 18 21:04:21 LABEEB3B systemd[1]: rgc.service: Main process exited, code=exit
Apr 18 21:04:21 LABEEB3B systemd[1]: rgc.service: Failed with result 'exit-code'
Apr 18 21:04:25 LABEEB3B systemd[1]: rgc.service: Service RestartSec=3s expired,
Apr 18 21:04:25 LABEEB3B systemd[1]: rgc.service: Scheduled restart job, restart
Apr 18 21:04:25 LABEEB3B systemd[1]: Stopped Remote GPIO Control Server.
Apr 18 21:04:25 LABEEB3B systemd[1]: Started Remote GPIO Control Server.
Apr 18 21:04:25 LABEEB3B python[872]: Traceback (most recent call last):
lines 1-23

**Comment by mdi-9** [comment]
Repeat all then:
```
sudo apt-get install python-dev python-crypto python-systemd python-pip postgresql libpq-dev postgresql-client 
sudo pip install psycopg2 psutil
```

**Comment by Labeeb97** [comment]
something wrong with he 2nd command:

pi@LABEEB3B:~ $ sudo apt-get install python-dev python-crypto python-systemd python-pip postgresql libpq-dev postgresql-client 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libpq-dev is already the newest version (11.11-0+deb10u1).
postgresql is already the newest version (11+200+deb10u4).
postgresql-client is already the newest version (11+200+deb10u4).
python-crypto is already the newest version (2.6.1-9+b1).
python-crypto set to manually installed.
python-dev is already the newest version (2.7.16-1).
python-dev set to manually installed.
python-systemd is already the newest version (234-2+b1).
python-pip is already the newest version (18.1-5+rpt1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@LABEEB3B:~ $ sudo pip install psycopg2 psutil
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting psycopg2
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)",)': /simple/psycopg2/
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='www.piwheels.org', port=443): Read timed out. (read timeout=15)",)': /simple/psycopg2/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='www.piwheels.org', port=443): Read timed out. (read timeout=15)",)': /simple/psycopg2/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='www.piwheels.org', port=443): Read timed out. (read timeout=15)",)': /simple/psycopg2/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='www.piwheels.org', port=443): Read timed out. (read timeout=15)",)': /simple/psycopg2/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='www.piwheels.org', port=443): Read timed out. (read timeout=15)",)': /simple/psycopg2/

**Comment by mdi-9** [comment]
repair connection to pypi (port 443) or install psycopg2 and psutil from source

**Comment by Labeeb97** [comment]
Sorry, I didn't know how/why to do all that. I just wanted to use your application. Would you please let me know why/how to do that? Why all that happening to install the application?

**Comment by mdi-9** [comment]
To install those packages u need to have working internet connection to site: https://pypi.org from pi device. I don't know your network setup, can't help, investigate on your own.

**Comment by Labeeb97** [comment]
Ok, i repaired the pypi (port 443) & now i got this:
pi@LABEEB3B:~ $ sudo systemctl restart rgc.service
pi@LABEEB3B:~ $ sudo systemctl status rgc.service
* rgc.service - Remote GPIO Control Server
   Loaded: loaded (/lib/systemd/system/rgc.service; enabled; vendor preset: enab
   Active: active (running) since Tue 2021-04-20 13:09:46 +04; 17ms ago
 Main PID: 2447 (python)
    Tasks: 1 (limit: 2062)
   CGroup: /system.slice/rgc.service
           `-2447 /usr/bin/python rgc-server.py

Apr 20 13:09:46 LABEEB3B systemd[1]: Started Remote GPIO Control Server.
lines 1-9/9 (END)
pi@LABEEB3B:~ $ journalctl -u rgc.service
-- Logs begin at Tue 2021-04-20 12:53:09 +04, end at Tue 2021-04-20 13:10:05 +04
Apr 20 12:53:21 LABEEB3B systemd[1]: Started Remote GPIO Control Server.
Apr 20 12:53:24 LABEEB3B python[572]: Server is starting...
Apr 20 12:53:24 LABEEB3B python[572]: Please press Ctrl+C to end the program...
Apr 20 12:53:24 LABEEB3B python[572]: Traceback (most recent call last):
Apr 20 12:53:24 LABEEB3B python[572]:   File "rgc-server.py", line 1483, in <mod
Apr 20 12:53:24 LABEEB3B python[572]:     conn, conndb = newDBConnP()
Apr 20 12:53:24 LABEEB3B python[572]:   File "rgc-server.py", line 579, in newDB
Apr 20 12:53:24 LABEEB3B python[572]:     conn = psycopg2.connect(connectionStri
Apr 20 12:53:24 LABEEB3B python[572]:   File "/usr/local/lib/python2.7/dist-pack
Apr 20 12:53:24 LABEEB3B python[572]:     conn = _connect(dsn, connection_factor
Apr 20 12:53:24 LABEEB3B python[572]: psycopg2.OperationalError: could not conne
Apr 20 12:53:24 LABEEB3B python[572]:         Is the server running on host "loc
Apr 20 12:53:24 LABEEB3B python[572]:         TCP/IP connections on port 5432?
Apr 20 12:53:24 LABEEB3B python[572]: could not connect to server: Connection re
Apr 20 12:53:24 LABEEB3B python[572]:         Is the server running on host "loc
Apr 20 12:53:24 LABEEB3B python[572]:         TCP/IP connections on port 5432?
Apr 20 12:53:24 LABEEB3B systemd[1]: rgc.service: Main process exited, code=exit
Apr 20 12:53:24 LABEEB3B systemd[1]: rgc.service: Failed with result 'exit-code'
Apr 20 12:53:28 LABEEB3B systemd[1]: rgc.service: Service RestartSec=3s expired,
Apr 20 12:53:28 LABEEB3B systemd[1]: rgc.service: Scheduled restart job, restart
Apr 20 12:53:28 LABEEB3B systemd[1]: Stopped Remote GPIO Control Server.
Apr 20 12:53:28 LABEEB3B systemd[1]: Started Remote GPIO Control Server.
lines 1-23

**Comment by mdi-9** [comment]
Logs says that app cannot connect to postgre database.

Did U create it as it is in docs ? and configured rgc-config.ini ?

**Comment by Labeeb97** [comment]
I am sure I did. I will share that with you

**Comment by Labeeb97** [comment]
i tried to re do it & i got this:

pi@LABEEB3B:~ $ sudo apt install postgresql libpq-dev postgresql-client postgresql-client-common -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libpq-dev is already the newest version (11.11-0+deb10u1).
postgresql is already the newest version (11+200+deb10u4).
postgresql-client is already the newest version (11+200+deb10u4).
postgresql-client-common is already the newest version (200+deb10u4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@LABEEB3B:~ $ sudo su postgres
postgres@LABEEB3B:/home/pi$ createuser pi -P --interactive
Enter password for new role: 
Enter it again: 
Shall the new role be a superuser? (y/n) y
createuser: could not connect to database template1: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
postgres@LABEEB3B:/home/pi$

**Comment by mdi-9** [comment]
Port 5432 is locked ?

You have very badly configured firewall, all above problems leeds to locked ports. 
If U don't configure it properly there will be more problems later. Maybe disable it for installation time.

**Comment by clkdecember14** [comment]
I am having the same problem. Any solution?
![Uploading IMG_20210517_222934774~2.jpg…]()

**Comment by caseyKoehn** [comment]
I am having the same problem. Any solutions?
![IMG_20210517_222934774~2](https://user-images.githubusercontent.com/80666095/118595240-8ff66d80-b75f-11eb-8cff-780699e4bb13.jpg)

**Comment by mdi-9** [comment]
show me: journalctl -u rgc.service -r
